"use strict";                      // treat all js code as newer version. 

                                   //alert( 3 + 3 ); // we are using nodejs not browser

 console.log( 3 
    + 3 );                         // code readability should be high (NOT USE THIS STYLE IN REAL WORLD)

 console.log(" vansh ");           // USEEEEE THIS STYLE 


//TC39.JS org is the website where we can see all the new feature of js
//MDN WEB docs is the website where we can see all the documentation of js 

let name = "vansh";                     // string data type
let age = 18;                           // number data type
let isLoginIN = true;                   // boolean data type


// number => 2 to power 53
// bigint
// string => "" or '' 
// boolean => true or false
// null => empty value (standalone value)
// undefined => value is not assigned only varuable is declared
// symbol => unique and immutable data type ( used for unique identifliers )
// object =>collection of key value pairs (used for storing data in structured way)


console.log (typeof "vansh" );                        // string
console.log (typeof null);                            // OBJECT (this is a bug in JS but we can't change it now because of backward compatibility)
console.log (typeof undefined);                       // undefined
